## Numpy array and basic

In [2]:
import numpy as np

creating array from list [here array is from numpy, where list is array for python]

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[3,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [3 5 6]]


List vs numpy array

In [4]:
py_list = [1,2,3]
print(py_list*2)

np_array =np.array([1,2,3])
print(np_array*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print('Zeros array : \n',zeros)

ones = np.ones((3,4))
print('\n Ones array : \n',ones)

anySingleDigit = np.full((3,4),9)
print('\n digit array : \n',anySingleDigit)

random = np.random.random((3,4))
print('\n random array : \n',random)

sequence = np.arange(0,10,2)
print('\n sequence array : \n',sequence)



Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 digit array : 
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]

 random array : 
 [[0.10243454 0.15613315 0.43202493 0.43842392]
 [0.4236062  0.18561219 0.71959093 0.70186262]
 [0.43125384 0.32481542 0.56765648 0.13669813]]

 sequence array : 
 [0 2 4 6 8]


Vector Matix amd Tensor

In [6]:
vector = np.array([1,2,3])
print("vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print('Matrix : ',matrix)

tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print('tensor ',tensor)

vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
tensor  [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


Array Properties


In [7]:
arr =np.array([[1,2,3],[5,6,7]])

print('shape ',arr.shape)
print('dimension ',arr.ndim)
print('size ',arr.size)
print('data Type ',arr.dtype)

shape  (2, 3)
dimension  2
size  6
data Type  int64
