# Numpy Array's Operations


In [27]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing ",arr[2:7])
print('With step ',arr[0:8:2])
print('negative ',arr[-3])

basic slicing  [3 4 5 6 7]
With step  [1 3 5 7]
negative  8


In [29]:
arr_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print('specific element ',arr_2d[1,2])
print('Row ',arr_2d[1])
print('Colomn ',arr_2d[:,1])

specific element  6
Row  [4 5 6]
Colomn  [2 5 8]


## Sorting

In [30]:
unsorted = np.array([3,4,5,6,1,1,2,3,5,9])
print('sorted array',np.sort(unsorted))

arr_2d_unsorrted = np.array([[3,2],[1,2],[2,3]])
print('sorted 2d array axis 0 ',np.sort(arr_2d_unsorrted,axis=0))
print('sorted 2d array axis 1 ',np.sort(arr_2d_unsorrted,axis=1))

sorted array [1 1 2 3 3 4 5 5 6 9]
sorted 2d array axis 0  [[1 2]
 [2 2]
 [3 3]]
sorted 2d array axis 1  [[2 3]
 [1 2]
 [2 3]]


## Filter array

In [31]:
numbers = np.array([1,2,3,4,5,6,7,8])
even = numbers[numbers % 2 == 0]
print(even)

[2 4 6 8]


## Filter with Mask

In [32]:
mask = numbers>5
print('number greater than 5 ',numbers[mask])


number greater than 5  [6 7 8]


## Fancy indexing vs np.where()

In [33]:
indices = [0,2,3,4,6,4]
print(numbers[indices])

[1 3 4 5 7 5]


In [38]:
where_result = np.where(numbers>5)
print(numbers[where_result])

condition_result = np.where(numbers>4,numbers*10,numbers)
print(condition_result)


[6 7 8]
[ 1  2  3  4 50 60 70 80]


### Add and remove data and merge

In [41]:
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])

add = arr1 + arr2
print(add)

combined = np.concatenate((arr1,arr2))
print(combined)



[5 7 9]
[1 2 3 4 5 6]


### array compataibilty

In [43]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,0])

print('compatibitlity is ',a.shape == b.shape)
print('compatibitlity is ',c.shape == b.shape)

compatibitlity is  True
compatibitlity is  False


In [50]:
orignial = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orignial,new_row))
print('new row added \n',with_new_row)
new_col = np.array([[7],[8]])
with_new_col =np.hstack((orignial,new_col))
print('col added \n',with_new_col)

new row added 
 [[1 2]
 [3 4]
 [5 6]]
col added 
 [[1 2 7]
 [3 4 8]]


### Delete

In [53]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("after deleted ",deleted)
print('original ',arr)

after deleted  [1 2 4 5]
original  [1 2 3 4 5]
